columnSuffix: null
handle: aboutText1
instructions: 'about text first paragraph (required)'
name: 'About Text Paragraph 1'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
