columnSuffix: null
handle: categoryLabel
instructions: null
name: 'Category Label'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - News
        -
          - value
          - news
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Policy
        -
          - value
          - policy
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Data Report'
        -
          - value
          - data-report
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Events
        -
          - value
          - events
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - CAIC
        -
          - value
          - caic
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
