columnSuffix: null
handle: focusAreasPolicyCode
instructions: 'Bill or policy code (example: HB24-1012).'
name: 'Focus Areas Policy Code'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
