columnSuffix: null
handle: generalNewsItems
instructions: 'Select the resource entries that should appear in the General News section.'
name: 'General News Items'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add general news resource entries'
  showSearchInput: true
  showSiteMenu: true
  source: null
  sources:
    - 'section:41bfd232-738d-4745-aba7-36bff70c1ce4' # Resources
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
