columnSuffix: null
handle: getInvolvedCardOneLinkLabel
instructions: 'First participation card link label.'
name: 'Get Involved Card One Link Label'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
