columnSuffix: null
handle: getInvolvedHelpText
instructions: 'Body text in the bottom help section.'
name: 'Get Involved Help Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
