columnSuffix: null
handle: getInvolvedHelpButtonLabel
instructions: 'Button label in the bottom help section.'
name: 'Get Involved Help Button Label'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
