columnSuffix: null
handle: getInvolvedCardTwoText
instructions: 'Second participation card body text.'
name: 'Get Involved Card Two Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
