columnSuffix: null
handle: getInvolvedHeroDescriptionSecondary
instructions: 'Optional second paragraph under the Get Involved hero heading.'
name: 'Get Involved Hero Description Secondary'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
