columnSuffix: null
handle: getInvolvedWaysIntro
instructions: 'Intro text above the participation cards.'
name: 'Get Involved Ways Intro'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
