columnSuffix: null
handle: workgroupsSidebarText
instructions: 'Left column intro paragraph on the Workgroups page.'
name: 'Workgroups Sidebar Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
