defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 0c9a7a4c-1a6b-43de-aafe-15f7db84de0e # About Us
handle: aboutUs
maxAuthors: 1
name: 'About Us'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  8426bccd-8b8b-4dc4-93e7-f725ce1022b3: # CAIC Website
    enabledByDefault: true
    hasUrls: true
    template: about.twig
    uriFormat: about
type: single
