defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 7b8d5237-6d67-4377-9caa-617e33ec086a # Events
handle: eventsPage
maxAuthors: 1
name: Events
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  8426bccd-8b8b-4dc4-93e7-f725ce1022b3: # CAIC Website
    enabledByDefault: true
    hasUrls: true
    template: events/index.twig
    uriFormat: events
type: single
