defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: f08db00c-a26a-477f-bb00-efdbcdc19e2e # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  8426bccd-8b8b-4dc4-93e7-f725ce1022b3: # CAIC Website
    enabledByDefault: true
    hasUrls: true
    template: homepage/_entry.twig
    uriFormat: homepage
type: single
