defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 1b4f7c20-334e-4be2-b7d6-3b56e42a7f8c # Press Release
handle: pressReleases
maxAuthors: 1
name: 'Press Releases'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  8426bccd-8b8b-4dc4-93e7-f725ce1022b3: # CAIC Website
    enabledByDefault: true
    hasUrls: true
    template: news/_entry.twig
    uriFormat: 'press-releases/{slug}'
type: channel
